WE can perform mathematical operations on the entire elements without having to loop through the array


In [10]:
import numpy as np


In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [12]:
#ADDITION:
print(a + b)
#Each element will be added to its corresponding element

[5 7 9]


In [13]:
#SUBTRACTION:
print(b-a)

[3 3 3]


In [18]:
#DIVISION:
print(a/b)
print(b//a)

[0.25 0.4  0.5 ]
[4 2 2]


In [16]:
#MULTIPLICATION:
print(a*b)

[ 4 10 18]


In [19]:
#Modulus:
print(b%a)

[0 1 0]


In [20]:
#EVERY element raised to 2
print(a**2)

[1 4 9]
