In [2]:
import numpy as np

WE WANT TO CHANGE THE SHAPE OF THE ARRAY WITHOUT CHANGING THE DATA.

There are three ways to achieve this
1) Reshape
2) Ravel
3) Flatten

In [7]:
#RESHAPE
arr = np.array([1,2,3,4,5,6])
reshaped_arr = arr.reshape(6,1)#row*column must be equal to the number of elements.
print(reshaped_arr)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [12]:
#Ravel -> converts any array to 1D array.
#Changes are reflected to the oprignal array
Ravel = reshaped_arr.ravel()
print(Ravel)
print("--------------------------------------------------------")
print(reshaped_arr)
Ravel[0] = 100
print("--------------------------------------------------------")
print(Ravel)
print(reshaped_arr)


[1 2 3 4 5 6]
--------------------------------------------------------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
--------------------------------------------------------
[100   2   3   4   5   6]
[[100]
 [  2]
 [  3]
 [  4]
 [  5]
 [  6]]


In [14]:
#Flattens -> also like Ravel, but returns a copy
#Changes are not reflected to the orignal array.
flat = reshaped_arr.flatten()
flat

array([100,   2,   3,   4,   5,   6])