In [2]:
import numpy as np


#There are multiple ways to initialize a array


In [6]:
#FIRST METHOD
#np.arange(start,end,jump = 1)
ar = np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#SECOND METHOD
#Allows to create even spaced data seet,
#np.linspace(start,end, seperation between values)
ar2 = np.linspace(0,1,5)
ar2

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
#THIRD METHOD
#np.logspace(start,end,points)
ar3 = np.logspace(1,3,4) #10^1 -> 10^3 with four points in between
ar3

array([  10.        ,   46.41588834,  215.443469  , 1000.        ])

In [5]:
#Create a array full of zeros:
ar4 = np.zeros([2,3]) #array of zeros in two rows and three columns
print(ar4)
print("--------------------------------------------------------\n")
#Array of ones:
ar5 = np.ones([4,2],dtype = float)
print(ar5)
print("--------------------------------------------------------\n")

#Create a array full of any val
#np.full(number of values, value)
np.full(10,2)

[[0. 0. 0.]
 [0. 0. 0.]]
--------------------------------------------------------

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
--------------------------------------------------------



array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [22]:
#Random numbers with uniform distribution
np.random.rand(2,3) # returns float values between 0->1

array([[0.76436481, 0.06129622, 0.57546419],
       [0.22878028, 0.40387838, 0.23398978]])

In [23]:
#Generate random numbers with normal distribution, ie mean = 0 sd = 1
np.random.randn(2,3)

array([[ 2.12048104, -1.16304213, -0.18774068],
       [ 0.5583623 , -1.79127154, -0.04888743]])

In [26]:
#To produce array of random integers within an range:
np.random.randint(1,10, (2,3)) #start,stop,dimension

array([[3, 9, 3],
       [4, 7, 2]], dtype=int32)