In [1]:
import numpy as np

In [9]:
arr = np.array([[1,2],[4,5]])
arr

array([[1, 2],
       [4, 5]])

In [10]:
#TRANSPOSE:
print(arr.transpose())


[[1 4]
 [2 5]]


In [14]:
arr2 = np.array([[[1,2],[4,5]]])
print(arr2.shape)
swap = np.swapaxes(arr2, 0, 1)
print(swap.shape)
print(swap)

(1, 2, 2)
(2, 1, 2)
[[[1 2]]

 [[4 5]]]


In [15]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])


In [18]:
#Concatination: only works for 1d array
# con = np.concatenate(a,b)
# con
 #Vertical stacking:
print(np.vstack((a,b)))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
 #EDGE STACK::
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]
