A universal function (or ufunc for short) is a function that operates on ndarrays in an element-by-element fashion, supporting array broadcasting, type casting, and several other standard features. That is, a ufunc is a “vectorized” wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs


In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,4,9,16])
arr1

array([ 1,  4,  9, 16])

In [5]:
#SQRT FUNC
print(np.sqrt(arr1))

[1. 2. 3. 4.]


In [7]:
#EXPONENTION:
print(np.exp(arr1))# return e^x, where e is exponential and x is the element


[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [9]:
#SINE function: np.sine()
arr2 = np.array([0,np.pi, np.pi/2])
print(np.sin(arr2))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


In [14]:
#TO iterate through a numpy array we use np.iter()
arr3 = np.array([[1,2],[4,5]])
for x in np.nditer(arr3):
    print(x, end = " ")

#ndenumerate -> index + values.


1 2 4 5 