View = changes are reflected upon the orignal array

copy =  changes are only applied to the new array or the copy array

In [1]:
import numpy as np


In [3]:
arr = np.array([1,2,3,4,5,6])
view = arr[1:3]
view

array([2, 3])

In [4]:
view[0] = 200#this will also change the values in the orignal array
print(view)
print(arr)

[200   3]
[  1 200   3   4   5   6]


In [5]:
copy = arr[1:3].copy()
copy[0] = 2#this will not change the orignal arr
print(copy)
print(arr)

[2 3]
[  1 200   3   4   5   6]
